name: Go package

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
      - name: Test
        run: make test